version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      - REPLICA_URLS=http://replica1:5000,http://replica2:5000,http://replica3:5000
    depends_on:
      replica1: { condition: service_healthy }
      replica2: { condition: service_healthy }
      replica3: { condition: service_healthy }
    networks:
      - raft-network

  # All replicas now build from the SAME folder: ./replica
  replica1:
    build:
      context: ./replica
    environment:
      - REPLICA_ID=1
      - PEERS=http://replica2:5000,http://replica3:5000
    networks:
      - raft-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s

  replica2:
    build:
      context: ./replica
    environment:
      - REPLICA_ID=2
      - PEERS=http://replica1:5000,http://replica3:5000
    networks:
      - raft-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s

  replica3:
    build:
      context: ./replica
    environment:
      - REPLICA_ID=3
      - PEERS=http://replica1:5000,http://replica2:5000
    networks:
      - raft-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s

networks:
  raft-network:
    driver: bridge
